import math
import os
import sys
import re
import config

def format_timestamp(seconds):
    seconds = max(0, seconds)
    h  = math.floor(seconds / 3600)
    m  = math.floor((seconds % 3600) / 60)
    s  = math.floor(seconds % 60)
    ms = math.floor((seconds - math.floor(seconds)) * 1000)
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"

def format_ass_timestamp(seconds):
    seconds = max(0, seconds)
    h  = int(seconds // 3600)
    m  = int((seconds % 3600) // 60)
    s  = int(seconds % 60)
    cs = int(round((seconds - int(seconds)) * 100))
    if cs >= 100: cs = 99
    return f"{h}:{m:02d}:{s:02d}.{cs:02d}"

def time_to_sec(t_str):
    t_str = t_str.replace('.', ',')
    if ',' not in t_str: t_str += ',000'
    h, m, s_ms = t_str.split(':')
    s, ms = s_ms.split(',')
    return int(h)*3600 + int(m)*60 + int(s) + int(ms)/1000.0

def clean_path(path):
    if not path: return ""
    return os.path.normpath(path.replace("\\\\", "\\").replace("//", "/"))

def detect_paired_file(filepath, file_type):
    if not filepath: return ""
    base = os.path.splitext(filepath)[0]
    if file_type == "video":
        for ext in ['.mp4', '.mkv', '.avi', '.ts', '.mov', '.wmv']:
            if os.path.exists(base + ext): return base + ext
    elif file_type == "srt":
        if os.path.exists(base + ".srt"): return base + ".srt"
    return ""

def get_available_subtitles(video_path):
    subs = []
    if video_path and os.path.exists(video_path):
        v_dir = os.path.dirname(video_path)
        if os.path.exists(v_dir):
            for f in os.listdir(v_dir):
                if f.lower().endswith(('.srt', '.ass')):
                    subs.append(os.path.normpath(os.path.join(v_dir, f)))
    if os.path.exists(config.SUB_DIR):
        for f in os.listdir(config.SUB_DIR):
            if f.lower().endswith(('.srt', '.ass')):
                subs.append(os.path.normpath(os.path.join(config.SUB_DIR, f)))
    return list(dict.fromkeys(subs))

def resource_path(relative_path):
    try:
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")
    return os.path.join(base_path, relative_path)

def parse_srt(filepath):
    with open(filepath, 'r', encoding='utf-8-sig') as f:
        content = f.read()
    blocks  = re.split(r'\n\s*\n', content.strip())
    parsed  = []
    for block in blocks:
        lines = block.split('\n')
        if len(lines) >= 3:
            times = lines[1].split(' --> ')
            if len(times) == 2:
                try:
                    parsed.append({
                        "index": lines[0].strip(),
                        "start": time_to_sec(times[0].strip()),
                        "end":   time_to_sec(times[1].strip()),
                        "text":  '\n'.join(lines[2:]).strip()
                    })
                except Exception:
                    pass
    return parsed

def hex_to_ass_color(hex_color, alpha=0):
    hx = hex_color.lstrip('#')
    if len(hx) == 3: hx = ''.join(c*2 for c in hx)
    r, g, b = int(hx[0:2], 16), int(hx[2:4], 16), int(hx[4:6], 16)
    return f"&H{alpha:02X}{b:02X}{g:02X}{r:02X}"

def generate_ass_content(segments, style):
    primary   = hex_to_ass_color(style['primary_color'])
    outline_c = hex_to_ass_color(style['outline_color'])
    bg_alpha  = 0x60 if style['background'] else 0xFF
    back      = hex_to_ass_color("#000000", alpha=bg_alpha)
    bold      = -1 if style['bold']   else 0
    italic    = -1 if style['italic'] else 0

    header = (
        "[Script Info]\n"
        "; Generated by Universal Subtitle Toolkit (VLC Edition)\n"
        "ScriptType: v4.00+\n"
        "WrapStyle: 0\n"
        "ScaledBorderAndShadow: yes\n"
        "PlayResX: 512\n"
        "PlayResY: 288\n\n"
        "[V4+ Styles]\n"
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
        "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
        "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
        "Alignment, MarginL, MarginR, MarginV, Encoding\n"
        f"Style: Default,{style['font_name']},{style['font_size']},"
        f"{primary},&H000000FF,{outline_c},{back},"
        f"{bold},{italic},0,0,100,100,0,0,1,"
        f"{style['outline']},{style['shadow']},{style['alignment']},10,10,10,1\n\n"
        "[Events]\n"
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"
    )

    events = ""
    for seg in segments:
        text = seg['text'].replace('\n', '\\N').strip()
        if text:
            events += (
                f"Dialogue: 0,"
                f"{format_ass_timestamp(seg['start'])},"
                f"{format_ass_timestamp(seg['end'])},"
                f"Default,,0,0,0,,{text}\n"
            )
    return header + events